### ISSUE TITLE
Master Services Agreement signage before placing order??

### ISSUE THREAD

**Issue by TonyTheTech** [TeamUbersmith/order-forms#5]
To utilize this feature, where do I add the agreement to be seen per the services?

Thank you.

**Comment by ubersmith** [comment]
## You can add MSAs through setup & admin as well as on the profile pages of individual client accounts.  If you have any other questions, let us know.  Thanks.

-boo van alstyne
ubersmith vp support

---- Original message ----

> To utilize this feature, where do I add the agreement to be seen per
> the services?
> 
> Thank you. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TeamUbersmith/order-forms/issues/5

To view this ticket online, log in to https://billing.ubersmith.com/ticket.php?ticket_id=307132

**Comment by TonyTheTech** [comment]
Thank you. Currently still on 2.3.x and this feature is not available which is why I could not find it.
